# Generated by Django 4.2.2 on 2023-06-20 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ids', models.TextField()),
                ('total_count', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('mailchimp', 'MailChimp'), ('smtp', 'SMTP'), ('sendgrid', 'SendGrid')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_domain', models.CharField(max_length=20)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('sms_count', models.IntegerField(default=0)),
                ('body', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
